---
- name: Router setup
  hosts: routers
  roles:
    - router

- name: Bootstrap k3s masters
  hosts: k3s_masters
  roles:
    - k3s_master
    - role: flux
      when: gitops_tool == 'flux'

- name: k3s worker setup
  hosts: k3s_workers
  roles:
    - k3s_worker