---
- name: Setup ipv4 forwarding
  ansible.builtin.sysctl:
    name: net.ipv4.conf.all.forwarding
    value: '1'
    state: present
    reload: yes

- name: Install frr packages
  ansible.builtin.apt:
    name: "{{ frr_packages }}"
    state: present

- name: Enable bgpd daemon
  ansible.builtin.replace:
    path: /etc/frr/daemons
    regexp: '^bgpd=no'
    replace: 'bgpd=yes'
  notify: reload frr

- name: Enable and start frr service
  ansible.builtin.systemd:
    name: frr
    enabled: true
    state: started

- name: Generate frr configuration file
  ansible.builtin.template:
    src: frr.conf.j2
    dest: /etc/frr/frr.conf
    owner: frr
    group: frr
    mode: '0640'
    backup: true
    validate: /usr/lib/frr/frr-reload.py --test --stdout %s
  notify: reload frr
